# Effective data visualization {#chapter5}

## Overview

Expand your data visualization knowledge and tool set beyond what we have seen and practiced so far. We will move beyond scatter plots and learn other effective ways to visualize data, as well as some general rules of thumb to follow when creating visualations. All visualization tasks this week will be applied to real world data sets.

## Learning Objectives
By the end of the chapter, students will be able to:

* Define the three key aspects of ggplot objects:
     - aesthetic mappings
     - geometric objects
     - scales
* Use the `ggplot2` function in R to create the following visualizations:
    - 2-D scatter plot
    - 2-D scatter plot with a third variable that stratifies the groups
    - count bar chart for multiple groups
    - proportion bar chart for multiple groups
    - stacked bar chart for multiple groups
* List the rules of thumb for effective visualizations 
* Given a visualization and a sentence describing it's intended task, evaluate it's effectiveness and suggest ways to improve the visualization with respect to that intended task      